name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # - name: clippy
      #   run: cargo clippy --all-targets --all-features -- -D warnings
      - name: test sync
        run: cd s3 && cargo test --features sync --features sync-rustls --features wasm
      - name: test async
        run: cd s3 && cargo test --features async
      - name: test async
        run: cd s3 && cargo test --features async-rustls
      - name: build wasm32
        run: cd s3 && rustup target add wasm32-unknown-unknown && cargo build --target wasm32-unknown-unknown --features wasm
      - name: run simple_crud
        if: github.repository == 'durch/rust-s3'
        env:
          EU_AWS_ACCESS_KEY_ID: ${{ secrets.EU_AWS_ACCESS_KEY_ID }}
          EU_AWS_SECRET_ACCESS_KEY: ${{ secrets.EU_AWS_SECRET_ACCESS_KEY }}
        run: cd s3 && cargo run --bin simple_crud --features sync
